# An R script to generate graphs for Apache accesses. Histograms are drawn
# for the number per second, per 5 seconds, per 60 seconds, and per hour.

# R --no-save --args may31.csv < rps_daygraph.r

# Set this to the path to your CSV generated by apache_rps.sh if you don't
# want to use the command line.
csv <- commandArgs(trailingOnly = TRUE)[1];

# Set this to whatever your Apache MaxClients setting is set to. This just
# draws a line indicating where your server might be overloaded.
max_clients <- 50;

# Return a moving average based off of the last n items.
ma <- function(x, n=5) {
  filter(x,rep(1/n,n), sides=1)
}

rps <- read.csv(file=csv, head=TRUE, sep=",");
a <- ma(rps$requests_per_second, 5);

png(filename="rps-may-31.png", width=800, height=600, units="px", pointsize = 12);

plot(rps$requests_per_second, col="darkblue", xlab="Time", ylab="Requests", xaxt="n", type="h");
a <- ma(rps$requests_per_second, 5);
lines(a, col="green", type="h");
a <- ma(rps$requests_per_second, 60);
lines(a, col="red", type="h");
a <- ma(rps$requests_per_second, 3600);
lines(a, col="yellow", type="h");
legend("topleft", c("Per second", "Per 5 seconds", "Per minute", "Per hour"), col=c("darkblue", "green", "red", "yellow"), lty=1, lwd=2);

hours <- rps$date[seq(1, length(rps$date), 3600)];
axis(1, at=seq(0, 3600*23, 3600), hours);

abline(max_clients, 0);
dev.off();

